# MUST EDIT BELOW
sitename: Kitchen Table Coders
tagline: Workshops on the craft of creative coding in all its forms
url: http://kitchentablecoders.github.com
ga: UA-XXXXX-X              #Google Analytics ID
sitemap: GOOGLEWEBMASTER    #Google webmaster verification code
# END
# CHOOSE YOUR PREFERENCE
pygments:    true
markdown:    maruku
permalink:   pretty
# END
exclude: [LICENSE, README.markdown, Rakefile]
